apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: mglm-sample-and-diagnosis-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: mglm-sample-and-diagnosis-webapi-config
    literals:
      - database=mglm-sample-and-diagnosis-test
      - collection=sample-and-diagnosis
