/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

import (
	"github.com/gin-gonic/gin"
)

type SampleReportsAPI interface {


    // DeleteSampleReport Delete /api/samples/:sampleId/report
    // Discards a preliminary diagnostic report 
     DeleteSampleReport(c *gin.Context)

    // FinalizeSampleReport Post /api/samples/:sampleId/report/finalize
    // Finalizes the diagnostic report 
     FinalizeSampleReport(c *gin.Context)

    // SaveSampleReport Put /api/samples/:sampleId/report
    // Saves a preliminary diagnostic report 
     SaveSampleReport(c *gin.Context)

}