/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

import (
	"github.com/gin-gonic/gin"
)

type SamplesAPI interface {


    // CreateSample Post /api/samples
    // Creates a technician sample draft 
     CreateSample(c *gin.Context)

    // DeleteSample Delete /api/samples/:sampleId
    // Deletes a non-finalized sample 
     DeleteSample(c *gin.Context)

    // GetSample Get /api/samples/:sampleId
    // Provides sample detail 
     GetSample(c *gin.Context)

    // GetSamples Get /api/samples
    // Provides samples 
     GetSamples(c *gin.Context)

    // UpdateSample Put /api/samples/:sampleId
    // Updates a technician draft sample 
     UpdateSample(c *gin.Context)

    // UpdateSampleStatus Patch /api/samples/:sampleId/status
    // Updates sample status 
     UpdateSampleStatus(c *gin.Context)

}