/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

import (
	"github.com/gin-gonic/gin"
)

type SampleMeasurementsAPI interface {


    // SaveSampleMeasurements Put /api/samples/:sampleId/measurements
    // Saves measured values for a sample 
     SaveSampleMeasurements(c *gin.Context)

}