/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

import (
	"github.com/gin-gonic/gin"
)

type PatientReportsAPI interface {


    // GetPatientReports Get /api/patients/:patientId/reports
    // Provides finalized reports for a patient 
     GetPatientReports(c *gin.Context)

}