/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

type TestType struct {

	Code string `json:"code"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	MeasurementSchema []MeasurementDefinition `json:"measurementSchema"`
}
