/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

import (
	"time"
)

type MeasurementValue struct {

	TestTypeCode string `json:"testTypeCode"`

	Code string `json:"code"`

	// Serialized measurement value. Interpret the value according to the referenced MeasurementDefinition.valueType.
	Value string `json:"value"`

	Unit string `json:"unit,omitempty"`

	MeasuredAt time.Time `json:"measuredAt,omitempty"`

	EnteredByRole string `json:"enteredByRole,omitempty"`
}
