/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

type MeasurementValueType string

// List of MeasurementValueType
const (
	NUMBER MeasurementValueType = "number"
	TEXT MeasurementValueType = "text"
	BOOLEAN MeasurementValueType = "boolean"
	SELECT MeasurementValueType = "select"
)
