/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

import (
	"time"
)

type Sample struct {

	Id string `json:"id"`

	PatientName string `json:"patientName"`

	PatientId string `json:"patientId,omitempty"`

	SampleCode string `json:"sampleCode"`

	CollectedAt time.Time `json:"collectedAt"`

	TestTypes []string `json:"testTypes"`

	Status SampleStatus `json:"status"`

	Measurements []MeasurementValue `json:"measurements"`

	Report DiagnosticReport `json:"report,omitempty"`

	CreatedAt time.Time `json:"createdAt"`

	UpdatedAt time.Time `json:"updatedAt"`

	CreatedBy string `json:"createdBy,omitempty"`

	FinalizedBy string `json:"finalizedBy,omitempty"`
}
