/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

type SampleStatus string

// List of SampleStatus
const (
	DRAFT SampleStatus = "draft"
	COLLECTED SampleStatus = "collected"
	IN_DIAGNOSTICS SampleStatus = "in_diagnostics"
	REPORT_DRAFT SampleStatus = "report_draft"
	FINALIZED SampleStatus = "finalized"
	TAINTED SampleStatus = "tainted"
)
