/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

import (
	"time"
)

type NewSample struct {

	PatientName string `json:"patientName"`

	PatientId string `json:"patientId,omitempty"`

	SampleCode string `json:"sampleCode"`

	CollectedAt time.Time `json:"collectedAt"`

	TestTypes []string `json:"testTypes"`
}
