/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

type MeasurementDefinition struct {

	Code string `json:"code"`

	Label string `json:"label"`

	ValueType MeasurementValueType `json:"valueType"`

	Unit string `json:"unit,omitempty"`

	Min float32 `json:"min,omitempty"`

	Max float32 `json:"max,omitempty"`

	Options []string `json:"options,omitempty"`

	Required bool `json:"required,omitempty"`
}
