/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

import (
	"time"
)

type DiagnosticReport struct {

	Id string `json:"id"`

	SampleId string `json:"sampleId"`

	PatientId string `json:"patientId,omitempty"`

	Summary string `json:"summary"`

	Conclusion string `json:"conclusion"`

	Recommendations string `json:"recommendations,omitempty"`

	CreatedAt time.Time `json:"createdAt"`

	UpdatedAt time.Time `json:"updatedAt"`

	FinalizedAt time.Time `json:"finalizedAt,omitempty"`

	Author string `json:"author,omitempty"`

	Status string `json:"status"`
}
