/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

type ReportDraft struct {

	Summary string `json:"summary"`

	Conclusion string `json:"conclusion"`

	Recommendations string `json:"recommendations,omitempty"`
}
