/*
 * Sample And Diagnosis API
 *
 * Sample collection, measurement, diagnostics, and patient documentation API.
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sample_and_diagnosis_test

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the PatientReportsAPI part of the API
	PatientReportsAPI PatientReportsAPI
	// Routes for the SampleMeasurementsAPI part of the API
	SampleMeasurementsAPI SampleMeasurementsAPI
	// Routes for the SampleReportsAPI part of the API
	SampleReportsAPI SampleReportsAPI
	// Routes for the SamplesAPI part of the API
	SamplesAPI SamplesAPI
	// Routes for the TestTypesAPI part of the API
	TestTypesAPI TestTypesAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"GetPatientReports",
			http.MethodGet,
			"/api/patients/:patientId/reports",
			handleFunctions.PatientReportsAPI.GetPatientReports,
		},
		{
			"SaveSampleMeasurements",
			http.MethodPut,
			"/api/samples/:sampleId/measurements",
			handleFunctions.SampleMeasurementsAPI.SaveSampleMeasurements,
		},
		{
			"DeleteSampleReport",
			http.MethodDelete,
			"/api/samples/:sampleId/report",
			handleFunctions.SampleReportsAPI.DeleteSampleReport,
		},
		{
			"FinalizeSampleReport",
			http.MethodPost,
			"/api/samples/:sampleId/report/finalize",
			handleFunctions.SampleReportsAPI.FinalizeSampleReport,
		},
		{
			"SaveSampleReport",
			http.MethodPut,
			"/api/samples/:sampleId/report",
			handleFunctions.SampleReportsAPI.SaveSampleReport,
		},
		{
			"CreateSample",
			http.MethodPost,
			"/api/samples",
			handleFunctions.SamplesAPI.CreateSample,
		},
		{
			"DeleteSample",
			http.MethodDelete,
			"/api/samples/:sampleId",
			handleFunctions.SamplesAPI.DeleteSample,
		},
		{
			"GetSample",
			http.MethodGet,
			"/api/samples/:sampleId",
			handleFunctions.SamplesAPI.GetSample,
		},
		{
			"GetSamples",
			http.MethodGet,
			"/api/samples",
			handleFunctions.SamplesAPI.GetSamples,
		},
		{
			"UpdateSample",
			http.MethodPut,
			"/api/samples/:sampleId",
			handleFunctions.SamplesAPI.UpdateSample,
		},
		{
			"UpdateSampleStatus",
			http.MethodPatch,
			"/api/samples/:sampleId/status",
			handleFunctions.SamplesAPI.UpdateSampleStatus,
		},
		{
			"GetTestTypes",
			http.MethodGet,
			"/api/test-types",
			handleFunctions.TestTypesAPI.GetTestTypes,
		},
	}
}
